const withEmoji = {
  AD: {
    name: 'Andorra',
    native: 'Andorra',
    phone: '376',
    currency: 'EUR',
    languages: ['ca'],
    emoji: '🇦🇩',
    emojiU: 'U+1F1E6 U+1F1E9',
  },
  AE: {
    name: 'United Arab Emirates',
    native: 'دولة الإمارات العربية المتحدة',
    phone: '971',
    currency: 'AED',
    languages: ['ar'],
    emoji: '🇦🇪',
    emojiU: 'U+1F1E6 U+1F1EA',
  },
  AF: {
    name: 'Afghanistan',
    native: 'افغانستان',
    phone: '93',
    currency: 'AFN',
    languages: ['ps', 'uz', 'tk'],
    emoji: '🇦🇫',
    emojiU: 'U+1F1E6 U+1F1EB',
  },
  AG: {
    name: 'Antigua and Barbuda',
    native: 'Antigua and Barbuda',
    phone: '1268',
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇦🇬',
    emojiU: 'U+1F1E6 U+1F1EC',
  },
  AI: {
    name: 'Anguilla',
    native: 'Anguilla',
    phone: '1264',
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇦🇮',
    emojiU: 'U+1F1E6 U+1F1EE',
  },
  AL: {
    name: 'Albania',
    native: 'Shqipëria',
    phone: '355',
    currency: 'ALL',
    languages: ['sq'],
    emoji: '🇦🇱',
    emojiU: 'U+1F1E6 U+1F1F1',
  },
  AM: {
    name: 'Armenia',
    native: 'Հայաստան',
    phone: '374',
    currency: 'AMD',
    languages: ['hy', 'ru'],
    emoji: '🇦🇲',
    emojiU: 'U+1F1E6 U+1F1F2',
  },
  AO: {
    name: 'Angola',
    native: 'Angola',
    phone: '244',
    currency: 'AOA',
    languages: ['pt'],
    emoji: '🇦🇴',
    emojiU: 'U+1F1E6 U+1F1F4',
  },
  AR: {
    name: 'Argentina',
    native: 'Argentina',
    phone: '54',
    currency: 'ARS',
    languages: ['es', 'gn'],
    emoji: '🇦🇷',
    emojiU: 'U+1F1E6 U+1F1F7',
  },
  AS: {
    name: 'American Samoa',
    native: 'American Samoa',
    phone: '1684',
    currency: 'USD',
    languages: ['en', 'sm'],
    emoji: '🇦🇸',
    emojiU: 'U+1F1E6 U+1F1F8',
  },
  AT: {
    name: 'Austria',
    native: 'Österreich',
    phone: '43',
    currency: 'EUR',
    languages: ['de'],
    emoji: '🇦🇹',
    emojiU: 'U+1F1E6 U+1F1F9',
  },
  AU: {
    name: 'Australia',
    native: 'Australia',
    phone: '61',
    currency: 'AUD',
    languages: ['en'],
    emoji: '🇦🇺',
    emojiU: 'U+1F1E6 U+1F1FA',
  },
  AW: {
    name: 'Aruba',
    native: 'Aruba',
    phone: '297',
    currency: 'AWG',
    languages: ['nl', 'pa'],
    emoji: '🇦🇼',
    emojiU: 'U+1F1E6 U+1F1FC',
  },
  AX: {
    name: 'Åland',
    native: 'Åland',
    phone: '358',
    currency: 'EUR',
    languages: ['sv'],
    emoji: '🇦🇽',
    emojiU: 'U+1F1E6 U+1F1FD',
  },
  AZ: {
    name: 'Azerbaijan',
    native: 'Azərbaycan',
    phone: '994',
    currency: 'AZN',
    languages: ['az'],
    emoji: '🇦🇿',
    emojiU: 'U+1F1E6 U+1F1FF',
  },
  BA: {
    name: 'Bosnia and Herzegovina',
    native: 'Bosna i Hercegovina',
    phone: '387',
    currency: 'BAM',
    languages: ['bs', 'hr', 'sr'],
    emoji: '🇧🇦',
    emojiU: 'U+1F1E7 U+1F1E6',
  },
  BB: {
    name: 'Barbados',
    native: 'Barbados',
    phone: '1246',
    currency: 'BBD',
    languages: ['en'],
    emoji: '🇧🇧',
    emojiU: 'U+1F1E7 U+1F1E7',
  },
  BD: {
    name: 'Bangladesh',
    native: 'Bangladesh',
    phone: '880',
    currency: 'BDT',
    languages: ['bn'],
    emoji: '🇧🇩',
    emojiU: 'U+1F1E7 U+1F1E9',
  },
  BE: {
    name: 'Belgium',
    native: 'België',
    phone: '32',
    currency: 'EUR',
    languages: ['nl', 'fr', 'de'],
    emoji: '🇧🇪',
    emojiU: 'U+1F1E7 U+1F1EA',
  },
  BF: {
    name: 'Burkina Faso',
    native: 'Burkina Faso',
    phone: '226',
    currency: 'XOF',
    languages: ['fr', 'ff'],
    emoji: '🇧🇫',
    emojiU: 'U+1F1E7 U+1F1EB',
  },
  BG: {
    name: 'Bulgaria',
    native: 'България',
    phone: '359',
    currency: 'BGN',
    languages: ['bg'],
    emoji: '🇧🇬',
    emojiU: 'U+1F1E7 U+1F1EC',
  },
  BH: {
    name: 'Bahrain',
    native: '‏البحرين',
    phone: '973',
    currency: 'BHD',
    languages: ['ar'],
    emoji: '🇧🇭',
    emojiU: 'U+1F1E7 U+1F1ED',
  },
  BI: {
    name: 'Burundi',
    native: 'Burundi',
    phone: '257',
    currency: 'BIF',
    languages: ['fr', 'rn'],
    emoji: '🇧🇮',
    emojiU: 'U+1F1E7 U+1F1EE',
  },
  BJ: {
    name: 'Benin',
    native: 'Bénin',
    phone: '229',
    currency: 'XOF',
    languages: ['fr'],
    emoji: '🇧🇯',
    emojiU: 'U+1F1E7 U+1F1EF',
  },
  BL: {
    name: 'Saint Barthélemy',
    native: 'Saint-Barthélemy',
    phone: '590',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇧🇱',
    emojiU: 'U+1F1E7 U+1F1F1',
  },
  BM: {
    name: 'Bermuda',
    native: 'Bermuda',
    phone: '1441',
    currency: 'BMD',
    languages: ['en'],
    emoji: '🇧🇲',
    emojiU: 'U+1F1E7 U+1F1F2',
  },
  BN: {
    name: 'Brunei',
    native: 'Negara Brunei Darussalam',
    phone: '673',
    currency: 'BND',
    languages: ['ms'],
    emoji: '🇧🇳',
    emojiU: 'U+1F1E7 U+1F1F3',
  },
  BO: {
    name: 'Bolivia',
    native: 'Bolivia',
    phone: '591',
    currency: 'BOB,BOV',
    languages: ['es', 'ay', 'qu'],
    emoji: '🇧🇴',
    emojiU: 'U+1F1E7 U+1F1F4',
  },
  BQ: {
    name: 'Bonaire',
    native: 'Bonaire',
    phone: '5997',
    currency: 'USD',
    languages: ['nl'],
    emoji: '🇧🇶',
    emojiU: 'U+1F1E7 U+1F1F6',
  },
  BR: {
    name: 'Brazil',
    native: 'Brasil',
    phone: '55',
    currency: 'BRL',
    languages: ['pt'],
    emoji: '🇧🇷',
    emojiU: 'U+1F1E7 U+1F1F7',
  },
  BS: {
    name: 'Bahamas',
    native: 'Bahamas',
    phone: '1242',
    currency: 'BSD',
    languages: ['en'],
    emoji: '🇧🇸',
    emojiU: 'U+1F1E7 U+1F1F8',
  },
  BT: {
    name: 'Bhutan',
    native: 'ʼbrug-yul',
    phone: '975',
    currency: 'BTN,INR',
    languages: ['dz'],
    emoji: '🇧🇹',
    emojiU: 'U+1F1E7 U+1F1F9',
  },
  BV: {
    name: 'Bouvet Island',
    native: 'Bouvetøya',
    phone: '47',
    currency: 'NOK',
    languages: ['no', 'nb', 'nn'],
    emoji: '🇧🇻',
    emojiU: 'U+1F1E7 U+1F1FB',
  },
  BW: {
    name: 'Botswana',
    native: 'Botswana',
    phone: '267',
    currency: 'BWP',
    languages: ['en', 'tn'],
    emoji: '🇧🇼',
    emojiU: 'U+1F1E7 U+1F1FC',
  },
  BY: {
    name: 'Belarus',
    native: 'Белару́сь',
    phone: '375',
    currency: 'BYN',
    languages: ['be', 'ru'],
    emoji: '🇧🇾',
    emojiU: 'U+1F1E7 U+1F1FE',
  },
  BZ: {
    name: 'Belize',
    native: 'Belize',
    phone: '501',
    currency: 'BZD',
    languages: ['en', 'es'],
    emoji: '🇧🇿',
    emojiU: 'U+1F1E7 U+1F1FF',
  },
  CA: {
    name: 'Canada',
    native: 'Canada',
    phone: '1',
    currency: 'CAD',
    languages: ['en', 'fr'],
    emoji: '🇨🇦',
    emojiU: 'U+1F1E8 U+1F1E6',
  },
  CC: {
    name: 'Cocos [Keeling] Islands',
    native: 'Cocos (Keeling) Islands',
    phone: '61',
    currency: 'AUD',
    languages: ['en'],
    emoji: '🇨🇨',
    emojiU: 'U+1F1E8 U+1F1E8',
  },
  CD: {
    name: 'Democratic Republic of the Congo',
    native: 'République démocratique du Congo',
    phone: '243',
    currency: 'CDF',
    languages: ['fr', 'ln', 'kg', 'sw', 'lu'],
    emoji: '🇨🇩',
    emojiU: 'U+1F1E8 U+1F1E9',
  },
  CF: {
    name: 'Central African Republic',
    native: 'Ködörösêse tî Bêafrîka',
    phone: '236',
    currency: 'XAF',
    languages: ['fr', 'sg'],
    emoji: '🇨🇫',
    emojiU: 'U+1F1E8 U+1F1EB',
  },
  CG: {
    name: 'Republic of the Congo',
    native: 'République du Congo',
    phone: '242',
    currency: 'XAF',
    languages: ['fr', 'ln'],
    emoji: '🇨🇬',
    emojiU: 'U+1F1E8 U+1F1EC',
  },
  CH: {
    name: 'Switzerland',
    native: 'Schweiz',
    phone: '41',
    currency: 'CHE,CHF,CHW',
    languages: ['de', 'fr', 'it'],
    emoji: '🇨🇭',
    emojiU: 'U+1F1E8 U+1F1ED',
  },
  CI: {
    name: 'Ivory Coast',
    native: "Côte d'Ivoire",
    phone: '225',
    currency: 'XOF',
    languages: ['fr'],
    emoji: '🇨🇮',
    emojiU: 'U+1F1E8 U+1F1EE',
  },
  CK: {
    name: 'Cook Islands',
    native: 'Cook Islands',
    phone: '682',
    currency: 'NZD',
    languages: ['en'],
    emoji: '🇨🇰',
    emojiU: 'U+1F1E8 U+1F1F0',
  },
  CL: {
    name: 'Chile',
    native: 'Chile',
    phone: '56',
    currency: 'CLF,CLP',
    languages: ['es'],
    emoji: '🇨🇱',
    emojiU: 'U+1F1E8 U+1F1F1',
  },
  CM: {
    name: 'Cameroon',
    native: 'Cameroon',
    phone: '237',
    currency: 'XAF',
    languages: ['en', 'fr'],
    emoji: '🇨🇲',
    emojiU: 'U+1F1E8 U+1F1F2',
  },
  CN: {
    name: 'China',
    native: '中国',
    phone: '86',
    currency: 'CNY',
    languages: ['zh'],
    emoji: '🇨🇳',
    emojiU: 'U+1F1E8 U+1F1F3',
  },
  CO: {
    name: 'Colombia',
    native: 'Colombia',
    phone: '57',
    currency: 'COP',
    languages: ['es'],
    emoji: '🇨🇴',
    emojiU: 'U+1F1E8 U+1F1F4',
  },
  CR: {
    name: 'Costa Rica',
    native: 'Costa Rica',
    phone: '506',
    currency: 'CRC',
    languages: ['es'],
    emoji: '🇨🇷',
    emojiU: 'U+1F1E8 U+1F1F7',
  },
  CU: {
    name: 'Cuba',
    native: 'Cuba',
    phone: '53',
    currency: 'CUC,CUP',
    languages: ['es'],
    emoji: '🇨🇺',
    emojiU: 'U+1F1E8 U+1F1FA',
  },
  CV: {
    name: 'Cape Verde',
    native: 'Cabo Verde',
    phone: '238',
    currency: 'CVE',
    languages: ['pt'],
    emoji: '🇨🇻',
    emojiU: 'U+1F1E8 U+1F1FB',
  },
  CW: {
    name: 'Curacao',
    native: 'Curaçao',
    phone: '5999',
    currency: 'ANG',
    languages: ['nl', 'pa', 'en'],
    emoji: '🇨🇼',
    emojiU: 'U+1F1E8 U+1F1FC',
  },
  CX: {
    name: 'Christmas Island',
    native: 'Christmas Island',
    phone: '61',
    currency: 'AUD',
    languages: ['en'],
    emoji: '🇨🇽',
    emojiU: 'U+1F1E8 U+1F1FD',
  },
  CY: {
    name: 'Cyprus',
    native: 'Κύπρος',
    phone: '357',
    currency: 'EUR',
    languages: ['el', 'tr', 'hy'],
    emoji: '🇨🇾',
    emojiU: 'U+1F1E8 U+1F1FE',
  },
  CZ: {
    name: 'Czech Republic',
    native: 'Česká republika',
    phone: '420',
    currency: 'CZK',
    languages: ['cs', 'sk'],
    emoji: '🇨🇿',
    emojiU: 'U+1F1E8 U+1F1FF',
  },
  DE: {
    name: 'Germany',
    native: 'Deutschland',
    phone: '49',
    currency: 'EUR',
    languages: ['de'],
    emoji: '🇩🇪',
    emojiU: 'U+1F1E9 U+1F1EA',
  },
  DJ: {
    name: 'Djibouti',
    native: 'Djibouti',
    phone: '253',
    currency: 'DJF',
    languages: ['fr', 'ar'],
    emoji: '🇩🇯',
    emojiU: 'U+1F1E9 U+1F1EF',
  },
  DK: {
    name: 'Denmark',
    native: 'Danmark',
    phone: '45',
    currency: 'DKK',
    languages: ['da'],
    emoji: '🇩🇰',
    emojiU: 'U+1F1E9 U+1F1F0',
  },
  DM: {
    name: 'Dominica',
    native: 'Dominica',
    phone: '1767',
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇩🇲',
    emojiU: 'U+1F1E9 U+1F1F2',
  },
  DO: {
    name: 'Dominican Republic',
    native: 'República Dominicana',
    phone: '1809,1829,1849',
    currency: 'DOP',
    languages: ['es'],
    emoji: '🇩🇴',
    emojiU: 'U+1F1E9 U+1F1F4',
  },
  DZ: {
    name: 'Algeria',
    native: 'الجزائر',
    phone: '213',
    currency: 'DZD',
    languages: ['ar'],
    emoji: '🇩🇿',
    emojiU: 'U+1F1E9 U+1F1FF',
  },
  EC: {
    name: 'Ecuador',
    native: 'Ecuador',
    phone: '593',
    currency: 'USD',
    languages: ['es'],
    emoji: '🇪🇨',
    emojiU: 'U+1F1EA U+1F1E8',
  },
  EE: {
    name: 'Estonia',
    native: 'Eesti',
    phone: '372',
    currency: 'EUR',
    languages: ['et'],
    emoji: '🇪🇪',
    emojiU: 'U+1F1EA U+1F1EA',
  },
  EG: {
    name: 'Egypt',
    native: 'مصر‎',
    phone: '20',
    currency: 'EGP',
    languages: ['ar'],
    emoji: '🇪🇬',
    emojiU: 'U+1F1EA U+1F1EC',
  },
  EH: {
    name: 'Western Sahara',
    native: 'الصحراء الغربية',
    phone: '212',
    currency: 'MAD,DZD,MRU',
    languages: ['es'],
    emoji: '🇪🇭',
    emojiU: 'U+1F1EA U+1F1ED',
  },
  ER: {
    name: 'Eritrea',
    native: 'ኤርትራ',
    phone: '291',
    currency: 'ERN',
    languages: ['ti', 'ar', 'en'],
    emoji: '🇪🇷',
    emojiU: 'U+1F1EA U+1F1F7',
  },
  ES: {
    name: 'Spain',
    native: 'España',
    phone: '34',
    currency: 'EUR',
    languages: ['es', 'eu', 'ca', 'gl', 'oc'],
    emoji: '🇪🇸',
    emojiU: 'U+1F1EA U+1F1F8',
  },
  ET: {
    name: 'Ethiopia',
    native: 'ኢትዮጵያ',
    phone: '251',
    currency: 'ETB',
    languages: ['am'],
    emoji: '🇪🇹',
    emojiU: 'U+1F1EA U+1F1F9',
  },
  FI: {
    name: 'Finland',
    native: 'Suomi',
    phone: '358',
    currency: 'EUR',
    languages: ['fi', 'sv'],
    emoji: '🇫🇮',
    emojiU: 'U+1F1EB U+1F1EE',
  },
  FJ: {
    name: 'Fiji',
    native: 'Fiji',
    phone: '679',
    currency: 'FJD',
    languages: ['en', 'fj', 'hi', 'ur'],
    emoji: '🇫🇯',
    emojiU: 'U+1F1EB U+1F1EF',
  },
  FK: {
    name: 'Falkland Islands',
    native: 'Falkland Islands',
    phone: '500',
    currency: 'FKP',
    languages: ['en'],
    emoji: '🇫🇰',
    emojiU: 'U+1F1EB U+1F1F0',
  },
  FM: {
    name: 'Micronesia',
    native: 'Micronesia',
    phone: '691',
    currency: 'USD',
    languages: ['en'],
    emoji: '🇫🇲',
    emojiU: 'U+1F1EB U+1F1F2',
  },
  FO: {
    name: 'Faroe Islands',
    native: 'Føroyar',
    phone: '298',
    currency: 'DKK',
    languages: ['fo'],
    emoji: '🇫🇴',
    emojiU: 'U+1F1EB U+1F1F4',
  },
  FR: {
    name: 'France',
    native: 'France',
    phone: '33',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇫🇷',
    emojiU: 'U+1F1EB U+1F1F7',
  },
  GA: {
    name: 'Gabon',
    native: 'Gabon',
    phone: '241',
    currency: 'XAF',
    languages: ['fr'],
    emoji: '🇬🇦',
    emojiU: 'U+1F1EC U+1F1E6',
  },
  GB: {
    name: 'United Kingdom',
    native: 'United Kingdom',
    phone: '44',
    currency: 'GBP',
    languages: ['en'],
    emoji: '🇬🇧',
    emojiU: 'U+1F1EC U+1F1E7',
  },
  GD: {
    name: 'Grenada',
    native: 'Grenada',
    phone: '1473',
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇬🇩',
    emojiU: 'U+1F1EC U+1F1E9',
  },
  GE: {
    name: 'Georgia',
    native: 'საქართველო',
    phone: '995',
    currency: 'GEL',
    languages: ['ka'],
    emoji: '🇬🇪',
    emojiU: 'U+1F1EC U+1F1EA',
  },
  GF: {
    name: 'French Guiana',
    native: 'Guyane française',
    phone: '594',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇬🇫',
    emojiU: 'U+1F1EC U+1F1EB',
  },
  GG: {
    name: 'Guernsey',
    native: 'Guernsey',
    phone: '44',
    currency: 'GBP',
    languages: ['en', 'fr'],
    emoji: '🇬🇬',
    emojiU: 'U+1F1EC U+1F1EC',
  },
  GH: {
    name: 'Ghana',
    native: 'Ghana',
    phone: '233',
    currency: 'GHS',
    languages: ['en'],
    emoji: '🇬🇭',
    emojiU: 'U+1F1EC U+1F1ED',
  },
  GI: {
    name: 'Gibraltar',
    native: 'Gibraltar',
    phone: '350',
    currency: 'GIP',
    languages: ['en'],
    emoji: '🇬🇮',
    emojiU: 'U+1F1EC U+1F1EE',
  },
  GL: {
    name: 'Greenland',
    native: 'Kalaallit Nunaat',
    phone: '299',
    currency: 'DKK',
    languages: ['kl'],
    emoji: '🇬🇱',
    emojiU: 'U+1F1EC U+1F1F1',
  },
  GM: {
    name: 'Gambia',
    native: 'Gambia',
    phone: '220',
    currency: 'GMD',
    languages: ['en'],
    emoji: '🇬🇲',
    emojiU: 'U+1F1EC U+1F1F2',
  },
  GN: {
    name: 'Guinea',
    native: 'Guinée',
    phone: '224',
    currency: 'GNF',
    languages: ['fr', 'ff'],
    emoji: '🇬🇳',
    emojiU: 'U+1F1EC U+1F1F3',
  },
  GP: {
    name: 'Guadeloupe',
    native: 'Guadeloupe',
    phone: '590',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇬🇵',
    emojiU: 'U+1F1EC U+1F1F5',
  },
  GQ: {
    name: 'Equatorial Guinea',
    native: 'Guinea Ecuatorial',
    phone: '240',
    currency: 'XAF',
    languages: ['es', 'fr'],
    emoji: '🇬🇶',
    emojiU: 'U+1F1EC U+1F1F6',
  },
  GR: {
    name: 'Greece',
    native: 'Ελλάδα',
    phone: '30',
    currency: 'EUR',
    languages: ['el'],
    emoji: '🇬🇷',
    emojiU: 'U+1F1EC U+1F1F7',
  },
  GS: {
    name: 'South Georgia and the South Sandwich Islands',
    native: 'South Georgia',
    phone: '500',
    currency: 'GBP',
    languages: ['en'],
    emoji: '🇬🇸',
    emojiU: 'U+1F1EC U+1F1F8',
  },
  GT: {
    name: 'Guatemala',
    native: 'Guatemala',
    phone: '502',
    currency: 'GTQ',
    languages: ['es'],
    emoji: '🇬🇹',
    emojiU: 'U+1F1EC U+1F1F9',
  },
  GU: {
    name: 'Guam',
    native: 'Guam',
    phone: '1671',
    currency: 'USD',
    languages: ['en', 'ch', 'es'],
    emoji: '🇬🇺',
    emojiU: 'U+1F1EC U+1F1FA',
  },
  GW: {
    name: 'Guinea-Bissau',
    native: 'Guiné-Bissau',
    phone: '245',
    currency: 'XOF',
    languages: ['pt'],
    emoji: '🇬🇼',
    emojiU: 'U+1F1EC U+1F1FC',
  },
  GY: {
    name: 'Guyana',
    native: 'Guyana',
    phone: '592',
    currency: 'GYD',
    languages: ['en'],
    emoji: '🇬🇾',
    emojiU: 'U+1F1EC U+1F1FE',
  },
  HK: {
    name: 'Hong Kong',
    native: '香港',
    phone: '852',
    currency: 'HKD',
    languages: ['zh', 'en'],
    emoji: '🇭🇰',
    emojiU: 'U+1F1ED U+1F1F0',
  },
  HM: {
    name: 'Heard Island and McDonald Islands',
    native: 'Heard Island and McDonald Islands',
    phone: '61',
    currency: 'AUD',
    languages: ['en'],
    emoji: '🇭🇲',
    emojiU: 'U+1F1ED U+1F1F2',
  },
  HN: {
    name: 'Honduras',
    native: 'Honduras',
    phone: '504',
    currency: 'HNL',
    languages: ['es'],
    emoji: '🇭🇳',
    emojiU: 'U+1F1ED U+1F1F3',
  },
  HR: {
    name: 'Croatia',
    native: 'Hrvatska',
    phone: '385',
    currency: 'HRK',
    languages: ['hr'],
    emoji: '🇭🇷',
    emojiU: 'U+1F1ED U+1F1F7',
  },
  HT: {
    name: 'Haiti',
    native: 'Haïti',
    phone: '509',
    currency: 'HTG,USD',
    languages: ['fr', 'ht'],
    emoji: '🇭🇹',
    emojiU: 'U+1F1ED U+1F1F9',
  },
  HU: {
    name: 'Hungary',
    native: 'Magyarország',
    phone: '36',
    currency: 'HUF',
    languages: ['hu'],
    emoji: '🇭🇺',
    emojiU: 'U+1F1ED U+1F1FA',
  },
  ID: {
    name: 'Indonesia',
    native: 'Indonesia',
    phone: '62',
    currency: 'IDR',
    languages: ['id'],
    emoji: '🇮🇩',
    emojiU: 'U+1F1EE U+1F1E9',
  },
  IE: {
    name: 'Ireland',
    native: 'Éire',
    phone: '353',
    currency: 'EUR',
    languages: ['ga', 'en'],
    emoji: '🇮🇪',
    emojiU: 'U+1F1EE U+1F1EA',
  },
  IL: {
    name: 'Israel',
    native: 'יִשְׂרָאֵל',
    phone: '972',
    currency: 'ILS',
    languages: ['he', 'ar'],
    emoji: '🇮🇱',
    emojiU: 'U+1F1EE U+1F1F1',
  },
  IM: {
    name: 'Isle of Man',
    native: 'Isle of Man',
    phone: '44',
    currency: 'GBP',
    languages: ['en', 'gv'],
    emoji: '🇮🇲',
    emojiU: 'U+1F1EE U+1F1F2',
  },
  IN: {
    name: 'India',
    native: 'भारत',
    phone: '91',
    currency: 'INR',
    languages: ['hi', 'en'],
    emoji: '🇮🇳',
    emojiU: 'U+1F1EE U+1F1F3',
  },
  IO: {
    name: 'British Indian Ocean Territory',
    native: 'British Indian Ocean Territory',
    phone: '246',
    currency: 'USD',
    languages: ['en'],
    emoji: '🇮🇴',
    emojiU: 'U+1F1EE U+1F1F4',
  },
  IQ: {
    name: 'Iraq',
    native: 'العراق',
    phone: '964',
    currency: 'IQD',
    languages: ['ar', 'ku'],
    emoji: '🇮🇶',
    emojiU: 'U+1F1EE U+1F1F6',
  },
  IR: {
    name: 'Iran',
    native: 'ایران',
    phone: '98',
    currency: 'IRR',
    languages: ['fa'],
    emoji: '🇮🇷',
    emojiU: 'U+1F1EE U+1F1F7',
  },
  IS: {
    name: 'Iceland',
    native: 'Ísland',
    phone: '354',
    currency: 'ISK',
    languages: ['is'],
    emoji: '🇮🇸',
    emojiU: 'U+1F1EE U+1F1F8',
  },
  IT: {
    name: 'Italy',
    native: 'Italia',
    phone: '39',
    currency: 'EUR',
    languages: ['it'],
    emoji: '🇮🇹',
    emojiU: 'U+1F1EE U+1F1F9',
  },
  JE: {
    name: 'Jersey',
    native: 'Jersey',
    phone: '44',
    currency: 'GBP',
    languages: ['en', 'fr'],
    emoji: '🇯🇪',
    emojiU: 'U+1F1EF U+1F1EA',
  },
  JM: {
    name: 'Jamaica',
    native: 'Jamaica',
    phone: '1876',
    currency: 'JMD',
    languages: ['en'],
    emoji: '🇯🇲',
    emojiU: 'U+1F1EF U+1F1F2',
  },
  JO: {
    name: 'Jordan',
    native: 'الأردن',
    phone: '962',
    currency: 'JOD',
    languages: ['ar'],
    emoji: '🇯🇴',
    emojiU: 'U+1F1EF U+1F1F4',
  },
  JP: {
    name: 'Japan',
    native: '日本',
    phone: '81',
    currency: 'JPY',
    languages: ['ja'],
    emoji: '🇯🇵',
    emojiU: 'U+1F1EF U+1F1F5',
  },
  KE: {
    name: 'Kenya',
    native: 'Kenya',
    phone: '254',
    currency: 'KES',
    languages: ['en', 'sw'],
    emoji: '🇰🇪',
    emojiU: 'U+1F1F0 U+1F1EA',
  },
  KG: {
    name: 'Kyrgyzstan',
    native: 'Кыргызстан',
    phone: '996',
    currency: 'KGS',
    languages: ['ky', 'ru'],
    emoji: '🇰🇬',
    emojiU: 'U+1F1F0 U+1F1EC',
  },
  KH: {
    name: 'Cambodia',
    native: 'Kâmpŭchéa',
    phone: '855',
    currency: 'KHR',
    languages: ['km'],
    emoji: '🇰🇭',
    emojiU: 'U+1F1F0 U+1F1ED',
  },
  KI: {
    name: 'Kiribati',
    native: 'Kiribati',
    phone: '686',
    currency: 'AUD',
    languages: ['en'],
    emoji: '🇰🇮',
    emojiU: 'U+1F1F0 U+1F1EE',
  },
  KM: {
    name: 'Comoros',
    native: 'Komori',
    phone: '269',
    currency: 'KMF',
    languages: ['ar', 'fr'],
    emoji: '🇰🇲',
    emojiU: 'U+1F1F0 U+1F1F2',
  },
  KN: {
    name: 'Saint Kitts and Nevis',
    native: 'Saint Kitts and Nevis',
    phone: '1869',
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇰🇳',
    emojiU: 'U+1F1F0 U+1F1F3',
  },
  KP: {
    name: 'North Korea',
    native: '북한',
    phone: '850',
    currency: 'KPW',
    languages: ['ko'],
    emoji: '🇰🇵',
    emojiU: 'U+1F1F0 U+1F1F5',
  },
  KR: {
    name: 'South Korea',
    native: '대한민국',
    phone: '82',
    currency: 'KRW',
    languages: ['ko'],
    emoji: '🇰🇷',
    emojiU: 'U+1F1F0 U+1F1F7',
  },
  KW: {
    name: 'Kuwait',
    native: 'الكويت',
    phone: '965',
    currency: 'KWD',
    languages: ['ar'],
    emoji: '🇰🇼',
    emojiU: 'U+1F1F0 U+1F1FC',
  },
  KY: {
    name: 'Cayman Islands',
    native: 'Cayman Islands',
    phone: '1345',
    currency: 'KYD',
    languages: ['en'],
    emoji: '🇰🇾',
    emojiU: 'U+1F1F0 U+1F1FE',
  },
  KZ: {
    name: 'Kazakhstan',
    native: 'Қазақстан',
    phone: '76,77',
    currency: 'KZT',
    languages: ['kk', 'ru'],
    emoji: '🇰🇿',
    emojiU: 'U+1F1F0 U+1F1FF',
  },
  LA: {
    name: 'Laos',
    native: 'ສປປລາວ',
    phone: '856',
    currency: 'LAK',
    languages: ['lo'],
    emoji: '🇱🇦',
    emojiU: 'U+1F1F1 U+1F1E6',
  },
  LB: {
    name: 'Lebanon',
    native: 'لبنان',
    phone: '961',
    currency: 'LBP',
    languages: ['ar', 'fr'],
    emoji: '🇱🇧',
    emojiU: 'U+1F1F1 U+1F1E7',
  },
  LC: {
    name: 'Saint Lucia',
    native: 'Saint Lucia',
    phone: '1758',
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇱🇨',
    emojiU: 'U+1F1F1 U+1F1E8',
  },
  LI: {
    name: 'Liechtenstein',
    native: 'Liechtenstein',
    phone: '423',
    currency: 'CHF',
    languages: ['de'],
    emoji: '🇱🇮',
    emojiU: 'U+1F1F1 U+1F1EE',
  },
  LK: {
    name: 'Sri Lanka',
    native: 'śrī laṃkāva',
    phone: '94',
    currency: 'LKR',
    languages: ['si', 'ta'],
    emoji: '🇱🇰',
    emojiU: 'U+1F1F1 U+1F1F0',
  },
  LR: {
    name: 'Liberia',
    native: 'Liberia',
    phone: '231',
    currency: 'LRD',
    languages: ['en'],
    emoji: '🇱🇷',
    emojiU: 'U+1F1F1 U+1F1F7',
  },
  LS: {
    name: 'Lesotho',
    native: 'Lesotho',
    phone: '266',
    currency: 'LSL,ZAR',
    languages: ['en', 'st'],
    emoji: '🇱🇸',
    emojiU: 'U+1F1F1 U+1F1F8',
  },
  LT: {
    name: 'Lithuania',
    native: 'Lietuva',
    phone: '370',
    currency: 'EUR',
    languages: ['lt'],
    emoji: '🇱🇹',
    emojiU: 'U+1F1F1 U+1F1F9',
  },
  LU: {
    name: 'Luxembourg',
    native: 'Luxembourg',
    phone: '352',
    currency: 'EUR',
    languages: ['fr', 'de', 'lb'],
    emoji: '🇱🇺',
    emojiU: 'U+1F1F1 U+1F1FA',
  },
  LV: {
    name: 'Latvia',
    native: 'Latvija',
    phone: '371',
    currency: 'EUR',
    languages: ['lv'],
    emoji: '🇱🇻',
    emojiU: 'U+1F1F1 U+1F1FB',
  },
  LY: {
    name: 'Libya',
    native: '‏ليبيا',
    phone: '218',
    currency: 'LYD',
    languages: ['ar'],
    emoji: '🇱🇾',
    emojiU: 'U+1F1F1 U+1F1FE',
  },
  MA: {
    name: 'Morocco',
    native: 'المغرب',
    phone: '212',
    currency: 'MAD',
    languages: ['ar'],
    emoji: '🇲🇦',
    emojiU: 'U+1F1F2 U+1F1E6',
  },
  MC: {
    name: 'Monaco',
    native: 'Monaco',
    phone: '377',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇲🇨',
    emojiU: 'U+1F1F2 U+1F1E8',
  },
  MD: {
    name: 'Moldova',
    native: 'Moldova',
    phone: '373',
    currency: 'MDL',
    languages: ['ro'],
    emoji: '🇲🇩',
    emojiU: 'U+1F1F2 U+1F1E9',
  },
  ME: {
    name: 'Montenegro',
    native: 'Црна Гора',
    phone: '382',
    currency: 'EUR',
    languages: ['sr', 'bs', 'sq', 'hr'],
    emoji: '🇲🇪',
    emojiU: 'U+1F1F2 U+1F1EA',
  },
  MF: {
    name: 'Saint Martin',
    native: 'Saint-Martin',
    phone: '590',
    currency: 'EUR',
    languages: ['en', 'fr', 'nl'],
    emoji: '🇲🇫',
    emojiU: 'U+1F1F2 U+1F1EB',
  },
  MG: {
    name: 'Madagascar',
    native: 'Madagasikara',
    phone: '261',
    currency: 'MGA',
    languages: ['fr', 'mg'],
    emoji: '🇲🇬',
    emojiU: 'U+1F1F2 U+1F1EC',
  },
  MH: {
    name: 'Marshall Islands',
    native: 'M̧ajeļ',
    phone: '692',
    currency: 'USD',
    languages: ['en', 'mh'],
    emoji: '🇲🇭',
    emojiU: 'U+1F1F2 U+1F1ED',
  },
  MK: {
    name: 'North Macedonia',
    native: 'Северна Македонија',
    phone: '389',
    currency: 'MKD',
    languages: ['mk'],
    emoji: '🇲🇰',
    emojiU: 'U+1F1F2 U+1F1F0',
  },
  ML: {
    name: 'Mali',
    native: 'Mali',
    phone: '223',
    currency: 'XOF',
    languages: ['fr'],
    emoji: '🇲🇱',
    emojiU: 'U+1F1F2 U+1F1F1',
  },
  MM: {
    name: 'Myanmar [Burma]',
    native: 'မြန်မာ',
    phone: '95',
    currency: 'MMK',
    languages: ['my'],
    emoji: '🇲🇲',
    emojiU: 'U+1F1F2 U+1F1F2',
  },
  MN: {
    name: 'Mongolia',
    native: 'Монгол улс',
    phone: '976',
    currency: 'MNT',
    languages: ['mn'],
    emoji: '🇲🇳',
    emojiU: 'U+1F1F2 U+1F1F3',
  },
  MO: {
    name: 'Macao',
    native: '澳門',
    phone: '853',
    currency: 'MOP',
    languages: ['zh', 'pt'],
    emoji: '🇲🇴',
    emojiU: 'U+1F1F2 U+1F1F4',
  },
  MP: {
    name: 'Northern Mariana Islands',
    native: 'Northern Mariana Islands',
    phone: '1670',
    currency: 'USD',
    languages: ['en', 'ch'],
    emoji: '🇲🇵',
    emojiU: 'U+1F1F2 U+1F1F5',
  },
  MQ: {
    name: 'Martinique',
    native: 'Martinique',
    phone: '596',
    currency: 'EUR'
    languages: ['fr'],
    emoji: '🇲🇶',
    emojiU: 'U+1F1F2 U+1F1F6',
  },
  MR: {
    name: 'Mauritania',
    native: 'موريتانيا',
    phone: '222',
    currency: 'MRU',
    languages: ['ar'],
    emoji: '🇲🇷',
    emojiU: 'U+1F1F2 U+1F1F7',
  },
  MS: {
    name: 'Montserrat',
    native: 'Montserrat',
    phone: '1664',
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇲🇸',
    emojiU: 'U+1F1F2 U+1F1F8',
  },
  MT: {
    name: 'Malta',
    native: 'Malta',
    phone: '356',
    currency: 'EUR',
    languages: ['mt', 'en'],
    emoji: '🇲🇹',
    emojiU: 'U+1F1F2 U+1F1F9',
  },
  MU: {
    name: 'Mauritius',
    native: 'Maurice',
    phone: '230',
    currency: 'MUR',
    languages: ['en'],
    emoji: '🇲🇺',
    emojiU: 'U+1F1F2 U+1F1FA',
  },
  MV: {
    name: 'Maldives',
    native: 'Maldives',
    phone: '960',
    currency: 'MVR',
    languages: ['dv'],
    emoji: '🇲🇻',
    emojiU: 'U+1F1F2 U+1F1FB',
  },
  MW: {
    name: 'Malawi',
    native: 'Malawi',
    phone: '265',
    currency: 'MWK',
    languages: ['en', 'ny'],
    emoji: '🇲🇼',
    emojiU: 'U+1F1F2 U+1F1FC',
  },
  MX: {
    name: 'Mexico',
    native: 'México',
    phone: '52',
    currency: 'MXN',
    languages: ['es'],
    emoji: '🇲🇽',
    emojiU: 'U+1F1F2 U+1F1FD',
  },
  MY: {
    name: 'Malaysia',
    native: 'Malaysia',
    phone: '60',
    currency: 'MYR',
    languages: ['ms'],
    emoji: '🇲🇾',
    emojiU: 'U+1F1F2 U+1F1FE',
  },
  MZ: {
    name: 'Mozambique',
    native: 'Moçambique',
    phone: '258',
    currency: 'MZN',
    languages: ['pt'],
    emoji: '🇲🇿',
    emojiU: 'U+1F1F2 U+1F1FF',
  },
  NA: {
    name: 'Namibia',
    native: 'Namibia',
    phone: '264',
    currency: 'NAD,ZAR',
    languages: ['en', 'af'],
    emoji: '🇳🇦',
    emojiU: 'U+1F1F3 U+1F1E6',
  },
  NC: {
    name: 'New Caledonia',
    native: 'Nouvelle-Calédonie',
    phone: '687',
    currency: 'XPF',
    languages: ['fr'],
    emoji: '🇳🇨',
    emojiU: 'U+1F1F3 U+1F1E8',
  },
  NE: {
    name: 'Niger',
    native: 'Niger',
    phone: '227',
    currency: 'XOF',
    languages: ['fr'],
    emoji: '🇳🇪',
    emojiU: 'U+1F1F3 U+1F1EA',
  },
  NF: {
    name: 'Norfolk Island',
    native: 'Norfolk Island',
    phone: '672',
    currency: 'AUD',
    languages: ['en'],
    emoji: '🇳🇫',
    emojiU: 'U+1F1F3 U+1F1EB',
  },
  NG: {
    name: 'Nigeria',
    native: 'Nigeria',
    phone: '234',
    currency: 'NGN',
    languages: ['en'],
    emoji: '🇳🇬',
    emojiU: 'U+1F1F3 U+1F1EC',
  },
  NI: {
    name: 'Nicaragua',
    native: 'Nicaragua',
    phone: '505',
    currency: 'NIO',
    languages: ['es'],
    emoji: '🇳🇮',
    emojiU: 'U+1F1F3 U+1F1EE',
  },
  NL: {
    name: 'Netherlands',
    native: 'Nederland',
    phone: '31',
    currency: 'EUR',
    languages: ['nl'],
    emoji: '🇳🇱',
    emojiU: 'U+1F1F3 U+1F1F1',
  },
  NO: {
    name: 'Norway',
    native: 'Norge',
    phone: '47',
    currency: 'NOK',
    languages: ['no', 'nb', 'nn'],
    emoji: '🇳🇴',
    emojiU: 'U+1F1F3 U+1F1F4',
  },
  NP: {
    name: 'Nepal',
    native: 'नपल',
    phone: '977',
    currency: 'NPR',
    languages: ['ne'],
    emoji: '🇳🇵',
    emojiU: 'U+1F1F3 U+1F1F5',
  },
  NR: {
    name: 'Nauru',
    native: 'Nauru',
    phone: '674',
    currency: 'AUD',
    languages: ['en', 'na'],
    emoji: '🇳🇷',
    emojiU: 'U+1F1F3 U+1F1F7',
  },
  NU: {
    name: 'Niue',
    native: 'Niuē',
    phone: '683',
    currency: 'NZD',
    languages: ['en'],
    emoji: '🇳🇺',
    emojiU: 'U+1F1F3 U+1F1FA',
  },
  NZ: {
    name: 'New Zealand',
    native: 'New Zealand',
    phone: '64',
    currency: 'NZD',
    languages: ['en', 'mi'],
    emoji: '🇳🇿',
    emojiU: 'U+1F1F3 U+1F1FF',
  },
  OM: {
    name: 'Oman',
    native: 'عمان',
    phone: '968',
    currency: 'OMR',
    languages: ['ar'],
    emoji: '🇴🇲',
    emojiU: 'U+1F1F4 U+1F1F2',
  },
  PA: {
    name: 'Panama',
    native: 'Panamá',
    phone: '507',
    currency: 'PAB,USD',
    languages: ['es'],
    emoji: '🇵🇦',
    emojiU: 'U+1F1F5 U+1F1E6',
  },
  PE: {
    name: 'Peru',
    native: 'Perú',
    phone: '51',
    currency: 'PEN',
    languages: ['es'],
    emoji: '🇵🇪',
    emojiU: 'U+1F1F5 U+1F1EA',
  },
  PF: {
    name: 'French Polynesia',
    native: 'Polynésie française',
    phone: '689',
    currency: 'XPF',
    languages: ['fr'],
    emoji: '🇵🇫',
    emojiU: 'U+1F1F5 U+1F1EB',
  },
  PG: {
    name: 'Papua New Guinea',
    native: 'Papua Niugini',
    phone: '675',
    currency: 'PGK',
    languages: ['en'],
    emoji: '🇵🇬',
    emojiU: 'U+1F1F5 U+1F1EC',
  },
  PH: {
    name: 'Philippines',
    native: 'Pilipinas',
    phone: '63',
    currency: 'PHP',
    languages: ['en'],
    emoji: '🇵🇭',
    emojiU: 'U+1F1F5 U+1F1ED',
  },
  PK: {
    name: 'Pakistan',
    native: 'Pakistan',
    phone: '92',
    currency: 'PKR',
    languages: ['en', 'ur'],
    emoji: '🇵🇰',
    emojiU: 'U+1F1F5 U+1F1F0',
  },
  PL: {
    name: 'Poland',
    native: 'Polska',
    phone: '48',
    currency: 'PLN',
    languages: ['pl'],
    emoji: '🇵🇱',
    emojiU: 'U+1F1F5 U+1F1F1',
  },
  PM: {
    name: 'Saint Pierre and Miquelon',
    native: 'Saint-Pierre-et-Miquelon',
    phone: '508',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇵🇲',
    emojiU: 'U+1F1F5 U+1F1F2',
  },
  PN: {
    name: 'Pitcairn Islands',
    native: 'Pitcairn Islands',
    phone: '64',
    currency: 'NZD',
    languages: ['en'],
    emoji: '🇵🇳',
    emojiU: 'U+1F1F5 U+1F1F3',
  },
  PR: {
    name: 'Puerto Rico',
    native: 'Puerto Rico',
    phone: '1787,1939',
    currency: 'USD',
    languages: ['es', 'en'],
    emoji: '🇵🇷',
    emojiU: 'U+1F1F5 U+1F1F7',
  },
  PS: {
    name: 'Palestine',
    native: 'فلسطين',
    phone: '970',
    currency: 'ILS',
    languages: ['ar'],
    emoji: '🇵🇸',
    emojiU: 'U+1F1F5 U+1F1F8',
  },
  PT: {
    name: 'Portugal',
    native: 'Portugal',
    phone: '351',
    currency: 'EUR',
    languages: ['pt'],
    emoji: '🇵🇹',
    emojiU: 'U+1F1F5 U+1F1F9',
  },
  PW: {
    name: 'Palau',
    native: 'Palau',
    phone: '680',
    currency: 'USD',
    languages: ['en'],
    emoji: '🇵🇼',
    emojiU: 'U+1F1F5 U+1F1FC',
  },
  PY: {
    name: 'Paraguay',
    native: 'Paraguay',
    phone: '595',
    currency: 'PYG',
    languages: ['es', 'gn'],
    emoji: '🇵🇾',
    emojiU: 'U+1F1F5 U+1F1FE',
  },
  QA: {
    name: 'Qatar',
    native: 'قطر',
    phone: '974',
    currency: 'QAR',
    languages: ['ar'],
    emoji: '🇶🇦',
    emojiU: 'U+1F1F6 U+1F1E6',
  },
  RE: {
    name: 'Réunion',
    native: 'La Réunion',
    phone: '262',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇷🇪',
    emojiU: 'U+1F1F7 U+1F1EA',
  },
  RO: {
    name: 'Romania',
    native: 'România',
    phone: '40',
    currency: 'RON',
    languages: ['ro'],
    emoji: '🇷🇴',
    emojiU: 'U+1F1F7 U+1F1F4',
  },
  RS: {
    name: 'Serbia',
    native: 'Србија',
    phone: '381',
    currency: 'RSD',
    languages: ['sr'],
    emoji: '🇷🇸',
    emojiU: 'U+1F1F7 U+1F1F8',
  },
  RU: {
    name: 'Russia',
    native: 'Россия',
    phone: '7',
    currency: 'RUB',
    languages: ['ru'],
    emoji: '🇷🇺',
    emojiU: 'U+1F1F7 U+1F1FA',
  },
  RW: {
    name: 'Rwanda',
    native: 'Rwanda',
    phone: '250',
    currency: 'RWF',
    languages: ['rw', 'en', 'fr'],
    emoji: '🇷🇼',
    emojiU: 'U+1F1F7 U+1F1FC',
  },
  SA: {
    name: 'Saudi Arabia',
    native: 'العربية السعودية',
    phone: '966',
    currency: 'SAR',
    languages: ['ar'],
    emoji: '🇸🇦',
    emojiU: 'U+1F1F8 U+1F1E6',
  },
  SB: {
    name: 'Solomon Islands',
    native: 'Solomon Islands',
    phone: '677',
    currency: 'SBD',
    languages: ['en'],
    emoji: '🇸🇧',
    emojiU: 'U+1F1F8 U+1F1E7',
  },
  SC: {
    name: 'Seychelles',
    native: 'Seychelles',
    phone: '248',
    currency: 'SCR',
    languages: ['fr', 'en'],
    emoji: '🇸🇨',
    emojiU: 'U+1F1F8 U+1F1E8',
  },
  SD: {
    name: 'Sudan',
    native: 'السودان',
    phone: '249',
    currency: 'SDG',
    languages: ['ar', 'en'],
    emoji: '🇸🇩',
    emojiU: 'U+1F1F8 U+1F1E9',
  },
  SE: {
    name: 'Sweden',
    native: 'Sverige',
    phone: '46',
    currency: 'SEK',
    languages: ['sv'],
    emoji: '🇸🇪',
    emojiU: 'U+1F1F8 U+1F1EA',
  },
  SG: {
    name: 'Singapore',
    native: 'Singapore',
    phone: '65',
    currency: 'SGD',
    languages: ['en', 'ms', 'ta', 'zh'],
    emoji: '🇸🇬',
    emojiU: 'U+1F1F8 U+1F1EC',
  },
  SH: {
    name: 'Saint Helena',
    native: 'Saint Helena',
    phone: '290',
    currency: 'SHP',
    languages: ['en'],
    emoji: '🇸🇭',
    emojiU: 'U+1F1F8 U+1F1ED',
  },
  SI: {
    name: 'Slovenia',
    native: 'Slovenija',
    phone: '386',
    currency: 'EUR',
    languages: ['sl'],
    emoji: '🇸🇮',
    emojiU: 'U+1F1F8 U+1F1EE',
  },
  SJ: {
    name: 'Svalbard and Jan Mayen',
    native: 'Svalbard og Jan Mayen',
    phone: '4779',
    currency: 'NOK',
    languages: ['no'],
    emoji: '🇸🇯',
    emojiU: 'U+1F1F8 U+1F1EF',
  },
  SK: {
    name: 'Slovakia',
    native: 'Slovensko',
    phone: '421',
    currency: 'EUR',
    languages: ['sk'],
    emoji: '🇸🇰',
    emojiU: 'U+1F1F8 U+1F1F0',
  },
  SL: {
    name: 'Sierra Leone',
    native: 'Sierra Leone',
    phone: '232',
    currency: 'SLL',
    languages: ['en'],
    emoji: '🇸🇱',
    emojiU: 'U+1F1F8 U+1F1F1',
  },
  SM: {
    name: 'San Marino',
    native: 'San Marino',
    phone: '378',
    currency: 'EUR',
    languages: ['it'],
    emoji: '🇸🇲',
    emojiU: 'U+1F1F8 U+1F1F2',
  },
  SN: {
    name: 'Senegal',
    native: 'Sénégal',
    phone: '221',
    currency: 'XOF',
    languages: ['fr'],
    emoji: '🇸🇳',
    emojiU: 'U+1F1F8 U+1F1F3',
  },
  SO: {
    name: 'Somalia',
    native: 'Soomaaliya',
    phone: '252',
    currency: 'SOS',
    languages: ['so', 'ar'],
    emoji: '🇸🇴',
    emojiU: 'U+1F1F8 U+1F1F4',
  },
  SR: {
    name: 'Suriname',
    native: 'Suriname',
    phone: '597',
    currency: 'SRD',
    languages: ['nl'],
    emoji: '🇸🇷',
    emojiU: 'U+1F1F8 U+1F1F7',
  },
  SS: {
    name: 'South Sudan',
    native: 'South Sudan',
    phone: '211',
    currency: 'SSP',
    languages: ['en'],
    emoji: '🇸🇸',
    emojiU: 'U+1F1F8 U+1F1F8',
  },
  ST: {
    name: 'São Tomé and Príncipe',
    native: 'São Tomé e Príncipe',
    phone: '239',
    currency: 'STN',
    languages: ['pt'],
    emoji: '🇸🇹',
    emojiU: 'U+1F1F8 U+1F1F9',
  },
  SV: {
    name: 'El Salvador',
    native: 'El Salvador',
    phone: '503',
    currency: 'SVC,USD',
    languages: ['es'],
    emoji: '🇸🇻',
    emojiU: 'U+1F1F8 U+1F1FB',
  },
  SX: {
    name: 'Sint Maarten',
    native: 'Sint Maarten',
    phone: '1721',
    currency: 'ANG',
    languages: ['nl', 'en'],
    emoji: '🇸🇽',
    emojiU: 'U+1F1F8 U+1F1FD',
  },
  SY: {
    name: 'Syria',
    native: 'سوريا',
    phone: '963',
    currency: 'SYP',
    languages: ['ar'],
    emoji: '🇸🇾',
    emojiU: 'U+1F1F8 U+1F1FE',
  },
  SZ: {
    name: 'Swaziland',
    native: 'Swaziland',
    phone: '268',
    currency: 'SZL',
    languages: ['en', 'ss'],
    emoji: '🇸🇿',
    emojiU: 'U+1F1F8 U+1F1FF',
  },
  TC: {
    name: 'Turks and Caicos Islands',
    native: 'Turks and Caicos Islands',
    phone: '1649',
    currency: 'USD',
    languages: ['en'],
    emoji: '🇹🇨',
    emojiU: 'U+1F1F9 U+1F1E8',
  },
  TD: {
    name: 'Chad',
    native: 'Tchad',
    phone: '235',
    currency: 'XAF',
    languages: ['fr', 'ar'],
    emoji: '🇹🇩',
    emojiU: 'U+1F1F9 U+1F1E9',
  },
  TF: {
    name: 'French Southern Territories',
    native: 'Territoire des Terres australes et antarctiques fr',
    phone: '262',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇹🇫',
    emojiU: 'U+1F1F9 U+1F1EB',
  },
  TG: {
    name: 'Togo',
    native: 'Togo',
    phone: '228',
    currency: 'XOF',
    languages: ['fr'],
    emoji: '🇹🇬',
    emojiU: 'U+1F1F9 U+1F1EC',
  },
  TH: {
    name: 'Thailand',
    native: 'ประเทศไทย',
    phone: '66',
    currency: 'THB',
    languages: ['th'],
    emoji: '🇹🇭',
    emojiU: 'U+1F1F9 U+1F1ED',
  },
  TJ: {
    name: 'Tajikistan',
    native: 'Тоҷикистон',
    phone: '992',
    currency: 'TJS',
    languages: ['tg', 'ru'],
    emoji: '🇹🇯',
    emojiU: 'U+1F1F9 U+1F1EF',
  },
  TK: {
    name: 'Tokelau',
    native: 'Tokelau',
    phone: '690',
    currency: 'NZD',
    languages: ['en'],
    emoji: '🇹🇰',
    emojiU: 'U+1F1F9 U+1F1F0',
  },
  TL: {
    name: 'East Timor',
    native: 'Timor-Leste',
    phone: '670',
    currency: 'USD',
    languages: ['pt'],
    emoji: '🇹🇱',
    emojiU: 'U+1F1F9 U+1F1F1',
  },
  TM: {
    name: 'Turkmenistan',
    native: 'Türkmenistan',
    phone: '993',
    currency: 'TMT',
    languages: ['tk', 'ru'],
    emoji: '🇹🇲',
    emojiU: 'U+1F1F9 U+1F1F2',
  },
  TN: {
    name: 'Tunisia',
    native: 'تونس',
    phone: '216',
    currency: 'TND',
    languages: ['ar'],
    emoji: '🇹🇳',
    emojiU: 'U+1F1F9 U+1F1F3',
  },
  TO: {
    name: 'Tonga',
    native: 'Tonga',
    phone: '676',
    currency: 'TOP',
    languages: ['en', 'to'],
    emoji: '🇹🇴',
    emojiU: 'U+1F1F9 U+1F1F4',
  },
  TR: {
    name: 'Turkey',
    native: 'Türkiye',
    phone: '90',
    currency: 'TRY',
    languages: ['tr'],
    emoji: '🇹🇷',
    emojiU: 'U+1F1F9 U+1F1F7',
  },
  TT: {
    name: 'Trinidad and Tobago',
    native: 'Trinidad and Tobago',
    phone: '1868',
    currency: 'TTD',
    languages: ['en'],
    emoji: '🇹🇹',
    emojiU: 'U+1F1F9 U+1F1F9',
  },
  TV: {
    name: 'Tuvalu',
    native: 'Tuvalu',
    phone: '688',
    currency: 'AUD',
    languages: ['en'],
    emoji: '🇹🇻',
    emojiU: 'U+1F1F9 U+1F1FB',
  },
  TW: {
    name: 'Taiwan',
    native: '臺灣',
    phone: '886',
    currency: 'TWD',
    languages: ['zh'],
    emoji: '🇹🇼',
    emojiU: 'U+1F1F9 U+1F1FC',
  },
  TZ: {
    name: 'Tanzania',
    native: 'Tanzania',
    phone: '255',
    currency: 'TZS',
    languages: ['sw', 'en'],
    emoji: '🇹🇿',
    emojiU: 'U+1F1F9 U+1F1FF',
  },
  UA: {
    name: 'Ukraine',
    native: 'Україна',
    phone: '380',
    currency: 'UAH',
    languages: ['uk'],
    emoji: '🇺🇦',
    emojiU: 'U+1F1FA U+1F1E6',
  },
  UG: {
    name: 'Uganda',
    native: 'Uganda',
    phone: '256',
    currency: 'UGX',
    languages: ['en', 'sw'],
    emoji: '🇺🇬',
    emojiU: 'U+1F1FA U+1F1EC',
  },
  UM: {
    name: 'U.S. Minor Outlying Islands',
    native: 'United States Minor Outlying Islands',
    phone: '1',
    currency: 'USD',
    languages: ['en'],
    emoji: '🇺🇲',
    emojiU: 'U+1F1FA U+1F1F2',
  },
  US: {
    name: 'United States',
    native: 'United States',
    phone: '1',
    currency: 'USD,USN,USS',
    languages: ['en'],
    emoji: '🇺🇸',
    emojiU: 'U+1F1FA U+1F1F8',
  },
  UY: {
    name: 'Uruguay',
    native: 'Uruguay',
    phone: '598',
    currency: 'UYI,UYU',
    languages: ['es'],
    emoji: '🇺🇾',
    emojiU: 'U+1F1FA U+1F1FE',
  },
  UZ: {
    name: 'Uzbekistan',
    native: 'O‘zbekiston',
    phone: '998',
    currency: 'UZS',
    languages: ['uz', 'ru'],
    emoji: '🇺🇿',
    emojiU: 'U+1F1FA U+1F1FF',
  },
  VA: {
    name: 'Vatican City',
    native: 'Vaticano',
    phone: '379',
    currency: 'EUR',
    languages: ['it', 'la'],
    emoji: '🇻🇦',
    emojiU: 'U+1F1FB U+1F1E6',
  },
  VC: {
    name: 'Saint Vincent and the Grenadines',
    native: 'Saint Vincent and the Grenadines',
    phone: '1784',
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇻🇨',
    emojiU: 'U+1F1FB U+1F1E8',
  },
  VE: {
    name: 'Venezuela',
    native: 'Venezuela',
    phone: '58',
    currency: 'VES',
    languages: ['es'],
    emoji: '🇻🇪',
    emojiU: 'U+1F1FB U+1F1EA',
  },
  VG: {
    name: 'British Virgin Islands',
    native: 'British Virgin Islands',
    phone: '1284',
    currency: 'USD',
    languages: ['en'],
    emoji: '🇻🇬',
    emojiU: 'U+1F1FB U+1F1EC',
  },
  VI: {
    name: 'U.S. Virgin Islands',
    native: 'United States Virgin Islands',
    phone: '1340',
    currency: 'USD',
    languages: ['en'],
    emoji: '🇻🇮',
    emojiU: 'U+1F1FB U+1F1EE',
  },
  VN: {
    name: 'Vietnam',
    native: 'Việt Nam',
    phone: '84',
    currency: 'VND',
    languages: ['vi'],
    emoji: '🇻🇳',
    emojiU: 'U+1F1FB U+1F1F3',
  },
  VU: {
    name: 'Vanuatu',
    native: 'Vanuatu',
    phone: '678',
    currency: 'VUV',
    languages: ['bi', 'en', 'fr'],
    emoji: '🇻🇺',
    emojiU: 'U+1F1FB U+1F1FA',
  },
  WF: {
    name: 'Wallis and Futuna',
    native: 'Wallis et Futuna',
    phone: '681',
    currency: 'XPF',
    languages: ['fr'],
    emoji: '🇼🇫',
    emojiU: 'U+1F1FC U+1F1EB',
  },
  WS: {
    name: 'Samoa',
    native: 'Samoa',
    phone: '685',
    currency: 'WST',
    languages: ['sm', 'en'],
    emoji: '🇼🇸',
    emojiU: 'U+1F1FC U+1F1F8',
  },
  XK: {
    name: 'Kosovo',
    native: 'Republika e Kosovës',
    phone: '377,381,383,386',
    currency: 'EUR',
    languages: ['sq', 'sr'],
    emoji: '🇽🇰',
    emojiU: 'U+1F1FD U+1F1F0',
  },
  YE: {
    name: 'Yemen',
    native: 'اليَمَن',
    phone: '967',
    currency: 'YER',
    languages: ['ar'],
    emoji: '🇾🇪',
    emojiU: 'U+1F1FE U+1F1EA',
  },
  YT: {
    name: 'Mayotte',
    native: 'Mayotte',
    phone: '262',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇾🇹',
    emojiU: 'U+1F1FE U+1F1F9',
  },
  ZA: {
    name: 'South Africa',
    native: 'South Africa',
    phone: '27',
    currency: 'ZAR',
    languages: ['af', 'en', 'nr', 'st', 'ss', 'tn', 'ts', 've', 'xh', 'zu'],
    emoji: '🇿🇦',
    emojiU: 'U+1F1FF U+1F1E6',
  },
  ZM: {
    name: 'Zambia',
    native: 'Zambia',
    phone: '260',
    currency: 'ZMW',
    languages: ['en'],
    emoji: '🇿🇲',
    emojiU: 'U+1F1FF U+1F1F2',
  },
  ZW: {
    name: 'Zimbabwe',
    native: 'Zimbabwe',
    phone: '263',
    currency: 'USD,ZAR,BWP,GBP,AUD,CNY,INR,JPY',
    languages: ['en', 'sn', 'nd'],
    emoji: '🇿🇼',
    emojiU: 'U+1F1FF U+1F1FC',
  },
}
