/*
	Follows ISO 4217, https://www.iso.org/iso-4217-currency-codes.html
	See https://www.currency-iso.org/dam/downloads/lists/list_one.xml
	Data last updated 2020-06-30
*/

const localCurrencyData = {
  AED: {
    currency: 'Dirham',
    countries: ['United Arab Emirates'],
    locale: 'ar-AE',
    symbol: 'د.إ',
    unicode: 'U+060B',
    subunit: 'fils',
    number: '784',
    maximumFractionDigits: 2,
    minimumFractionDigits: 2,
    code: 'AED',
  },
  AFN: {
    countries: ['Afghanistan'],
    currency: 'Afghani',
    symbol: '؋',
    locale: '',
    fractionDigits: '2',
    numericCode: '971',
    subunit: '',
    maximumFractionDigits: '2',
    minimumFractionDigits: '2',
    code: 'AFN',
  },
  ALL: {
    countries: ['Albania'],
    currency: 'Lek',
    plural: 'Lekë',
    symbol: 'L',
    locale: 'sq-AL',
    fractionDigits: 2,
    numericCode: '008',
  },
  AMD: {
    countries: ['Armenia'],
    currency: 'Dram',
    plural: 'Dram',
    symbol: '֏',
    fractionDigits: 2,
    subunit: 'luma',
    code: 'AMD',
    number: '051',
  },
  ANG: {
    currency: 'Netherlands Antilles Guilder',
    locale: '',
    fractionDigits: 2,
    countries: ['Curaçao', 'Sint Maartin'],
    code: 'ANG',
    number: '532',
  },
  AOA: {
    countries: ['Angola'],
    currency: 'Kwanza',
    fractionDigits: 5,
    code: 'AOA',
    number: '973',
    digits: 2,
  },
  ARS: {
    countries: ['Argentina'],
    currency: 'Peso',
    locale: 'es-AR',
    fractionDigits: 2,
  },
  AUD: {
    countries: ['Australia'],
    currency: 'Dollar',
    locale: 'en-AU',
    subunit: 'cent',
    symbol: '$',
    fractionDigits: 2,
    numericCode: '036',
    unicode: 'U+0024',
  },
  AWG: {
    countries: ['Aruba'],
    currency: 'Guilder',
    locale: '',
    symbol: 'ƒ',
    fractionDigits: 5,
  },
  AZN: {
    countries: ['Azerbaijan'],
    currency: 'Manat',
    locale: 'az-AZ',
    symbol: '₼',
    fractionDigits: 5,
  },
  BAM: {
    countries: ['Bosnia and Herzegovina'],
    currency: 'Bosnia and Herzegovina Convertible Mark',
    locale: 'bs-BA',
    fractionDigits: 5,
  },
  BBD: {
    countries: ['Barbados'],
    currency: 'Dollar',
    plural: 'Dollars',
    symbol: '$',
    locale: '',
    fractionDigits: 5,
  },
  BDT: {
    countries: ['Bangladesh'],
    currency: 'Taka',
    locale: 'bn-BD',
    symbol: '',
    fractionDigits: 5,
  },
  BGN: {
    countries: ['Bulgaria'],
    currency: 'Lev',
    symbol: 'лв',
    locale: 'bg-BG',
    unicode: '',
    fractionDigits: 5,
  },
  BHD: {
    countries: ['Bahrain'],
    currency: 'Dinar',
    locale: '',
    symbol: '',
    unicode: '',
    fractionDigits: 5,
  },
  BIF: {
    countries: ['Burundi'],
    currency: 'Franc',
    locale: '',
    symbol: '',
    unicode: '',
    fractionDigits: 5,
  },
  BMD: {
    countries: ['Bermuda'],
    currency: 'Dollar',
    locale: '',
    symbol: '$',
    unicode: '',
    fractionDigits: 5,
  },
  BND: {
    countries: ['Brunei Darussalam'],
    currency: 'Dollar',
    locale: '',
    symbol: '$',
    unicode: '',
  },
  BOB: {
    countries: ['Bolivia'],
    currency: 'Bolíviano',
    locale: '',
    symbol: '',
    unicode: '',
  },
  BRL: {
    countries: ['Brazil'],
    currency: 'Real',
    locale: 'pt-BR',
    symbol: '',
    unicode: '',
  },
  BSD: {
    countries: ['Bahamas'],
    currency: 'Dollar',
    locale: '',
    symbol: '$',
    unicode: '',
  },
  BTN: {
    countries: ['Bhutan'],
    currency: 'Ngultrum',
    locale: '',
    symbol: '',
    unicode: '',
  },
  BWP: {
    countries: ['Botswana'],
    currency: 'Pula',
    locale: '',
    symbol: '',
    unicode: '',
  },
  BYN: {
    countries: ['Belarus'],
    currency: 'Ruble',
    locale: '',
    symbol: '',
  },
  BZD: {
    countries: ['Belize'],
    currency: 'Dollar',
    symbol: 'BZ$',
    locale: 'pt-BR',
  },
  CAD: {
    countries: ['Canada'],
    currency: 'Dollar',
    locale: 'en-CA',
    symbol: '$',
  },
  CDF: {
    countries: ['Congo/Kinshasa'],
    currency: 'Franc',
    locale: '',
    symbol: '',
  },
  CHF: {
    countries: ['Switzerland'],
    currency: 'Franc',
    locale: '',
    symbol: '',
  },
  CLP: {
    countries: ['Chile'],
    currency: 'Peso',
    locale: '',
    symbol: '',
  },
  CNY: {
    countries: ['China'],
    currency: 'Yuan Renminbi',
    locale: 'zh-CN',
  },
  COP: {
    countries: ['Colombia'],
    currency: 'Peso',
    locale: '',
    symbol: '',
    unicode: '',
  },
  CRC: {
    countries: ['Costa Rica'],
    currency: 'Colon',
    locale: 'es-CR',
    symbol: '₡',
  },
  CUC: {
    countries: ['Cuba'],
    currency: 'Convertible Peso',
    locale: 'es-',
    symbol: '$',
  },
  CUP: {
    countries: ['Cuba'],
    currency: 'Peso',
    locale: 'es-',
    symbol: '$',
  },
  CVE: {
    countries: ['Cape Verde'],
    currency: 'Escudo',
    locale: '',
  },
  CZK: {
    countries: ['Czech Republic'],
    currency: 'Koruna',
    locale: '',
  },
  DJF: {
    countries: ['Djibouti'],
    currency: 'Franc',
    locale: '',
  },
  DKK: {
    countries: ['Denmark'],
    currency: 'Krone',
    locale: 'da-DE',
  },
  DOP: {
    countries: ['Dominican Republic'],
    currency: 'Peso',
    locale: '',
  },
  DZD: {
    countries: ['Algeria'],
    currency: 'Dinar',
    locale: '',
  },
  EGP: {
    countries: ['Egypt'],
    currency: 'Pound',
    locale: '',
  },
  ERN: {
    countries: ['Eritrea'],
    currency: 'Nakfa',
    locale: '',
  },
  ETB: {
    countries: ['Ethiopia'],
    currency: 'Birr',
    locale: '',
  },
  EUR: {
    countries: ['Euro Member Countries'],
    currency: 'Euro',
    locale: 'de-DE',
    fractionDigits: 2,
    numericCode: '978',
  },
  FJD: {
    countries: ['Fiji'],
    currency: 'Dollar',
    symbol: 'FJ$',
    locale: 'en-FJ',
    fractionDigits: 2,
  },
  FKP: {
    countries: ['Falkland Islands (Malvinas)'],
    currency: 'Pound',
    locale: '',
  },
  GBP: {
    countries: ['United Kingdom'],
    currency: 'Pound',
    symbol: '£',
    locale: 'en-UK',
  },
  GEL: {
    countries: ['Georgia'],
    currency: 'Lari',
    locale: '',
  },
  GGP: {
    countries: ['Guernsey'],
    currency: 'Pound',
    locale: '',
  },
  GHS: {
    countries: ['Ghana'],
    currency: 'Cedi',
    symbol: '₵',
    locale: 'ee-GH',
  },
  GIP: {
    countries: ['Gibraltar'],
    currency: 'Pound',
    symbol: '',
    locale: '',
  },
  GMD: {
    countries: ['Gambia'],
    currency: 'Dalasi',
    locale: '',
    symbol: '',
  },
  GNF: {
    countries: ['Guinea'],
    currency: 'Franc',
    locale: '',
    symbol: '',
  },
  GTQ: {
    countries: ['Guatemala'],
    currency: 'Quetzal',
    symbol: 'Q',
    locale: 'es-GT',
  },
  GYD: {
    countries: ['Guyana'],
    currency: 'Dollar',
    locale: '',
    symbol: '$',
  },
  HKD: {
    countries: ['Hong Kong'],
    currency: 'Dollar',
    locale: 'zh-HK',
    symbol: '$',
  },
  HNL: {
    countries: ['Honduras'],
    currency: 'Lempira',
    locale: 'es-HN',
    symbol: 'L',
  },
  HRK: {
    countries: ['Croatia'],
    currency: 'Kuna',
    locale: '',
    symbol: '',
  },
  HTG: {
    countries: ['Haiti'],
    currency: 'Gourde',
    locale: '',
    symbol: '',
  },
  HUF: {
    countries: ['Hungary'],
    currency: 'Forint',
    locale: '',
    symbol: '',
  },
  IDR: {
    countries: ['Indonesia'],
    currency: 'Rupiah',
    locale: '',
    symbol: '',
  },
  ILS: {
    countries: ['Israel'],
    currency: 'Shekel',
    locale: '',
    symbol: '',
  },
  IMP: {
    countries: ['Isle of Man'],
    currency: 'Pound',
    locale: '',
    symbol: '',
    fractionDigits: 5,
  },
  INR: {
    countries: ['India'],
    currency: 'Rupee',
    symbol: '₹',
    locale: 'hi-IN',
    fractionDigits: 0,
  },
  IQD: {
    countries: ['Iraq'],
    currency: 'Dinar',
    locale: '',
    symbol: '',
  },
  IRR: {
    countries: ['Iran'],
    currency: 'Rial',
    locale: '',
    symbol: '',
  },
  ISK: {
    countries: ['Iceland'],
    currency: 'Krona',
    symbol: 'kr',
    locale: 'is-IS',
  },
  JEP: {
    countries: ['Jersey'],
    currency: 'Pound',
    symbol: '',
  },
  JMD: {
    countries: ['Jamaica'],
    currency: 'Dollar',
    symbol: '$',
  },
  JOD: {
    countries: ['Jordan'],
    currency: 'Dinar',
    locale: '',
  },
  JPY: {
    countries: ['Japan'],
    currency: 'Yen',
    locale: 'ja-JP',
  },
  KES: {
    countries: ['Kenya'],
    currency: 'Shilling',
    locale: '',
  },
  KGS: {
    countries: ['Kyrgyzstan'],
    currency: 'Som',
    locale: '',
    symbol: '',
  },
  KHR: {
    countries: ['Cambodia'],
    currency: 'Riel',
    locale: '',
    symbol: '',
  },
  KMF: {
    countries: ['Comorian'],
    currency: 'Franc',
    locale: '',
    symbol: '',
  },
  KPW: {
    countries: ['Korea (North)'],
    currency: 'Won',
    locale: 'ko-KR',
    symbol: '₩',
  },
  KRW: {
    countries: ['Korea (South)'],
    currency: 'Won',
    locale: 'ko-KR',
    symbol: '₩',
  },
  KWD: {
    countries: ['Kuwait'],
    currency: 'Dinar',
    locale: '',
    symbol: '',
  },
  KYD: {
    countries: ['Cayman Islands'],
    currency: 'Dollar',
    symbol: '$',
  },
  KZT: {
    countries: ['Kazakhstan'],
    currency: 'Tenge',
    locale: '',
    symbol: '',
  },
  LAK: {
    countries: ['Laos'],
    currency: 'Kip',
    locale: '',
    symbol: '',
  },
  LBP: {
    countries: ['Lebanon'],
    currency: 'Pound',
    locale: '',
    symbol: '',
  },
  LKR: {
    countries: ['Sri Lanka'],
    currency: 'Rupee',
    locale: '',
    symbol: '',
  },
  LRD: {
    countries: ['Liberia'],
    currency: 'Dollar',
    locale: '',
    symbol: '',
  },
  LSL: {
    countries: ['Lesotho'],
    currency: 'Loti',
    locale: '',
    symbol: '',
  },
  LYD: {
    countries: ['Libya'],
    currency: 'Dinar',
    locale: '',
    symbol: '',
  },
  MAD: {
    countries: ['Morocco'],
    currency: 'Dirham',
    locale: '',
    symbol: '',
  },
  MDL: {
    countries: ['Moldova'],
    currency: 'Leu',
    locale: '',
    symbol: '',
  },
  MGA: {
    countries: ['Madagascar'],
    currency: 'Ariary',
    locale: '',
    symbol: '',
  },
  MKD: {
    countries: ['Macedonia'],
    currency: 'Denar',
    locale: '',
    symbol: '',
  },
  MMK: {
    countries: ['Myanmar (Burma)'],
    currency: 'Kyat',
    locale: '',
    symbol: '',
  },
  MNT: {
    countries: ['Mongolia'],
    currency: 'Tughrik',
    locale: '',
    symbol: '',
  },
  MOP: {
    countries: ['Macau'],
    currency: 'Pataca',
    locale: '',
    symbol: '',
  },
  MRU: {
    countries: ['Mauritania'],
    currency: 'Ouguiya',
    locale: '',
    symbol: '',
  },
  MUR: {
    countries: ['Mauritius'],
    currency: 'Rupee',
    locale: '',
    symbol: '',
  },
  MVR: {
    countries: ['Maldives (Maldive Islands)'],
    currency: 'Rufiyaa',
    locale: '',
    symbol: '',
  },
  MWK: {
    countries: ['Malawi'],
    currency: 'Kwacha',
    locale: '',
    symbol: '',
  },
  MXN: {
    countries: ['Mexico'],
    currency: 'Peso',
    locale: 'es-MX',
    symbol: '$',
  },
  MYR: {
    countries: ['Malaysia'],
    currency: 'Ringgit',
  },
  MZN: {
    countries: ['Mozambique'],
    currency: 'Metical',
    locale: '',
    symbol: '',
  },
  NAD: {
    countries: ['Namibia'],
    currency: 'Dollar',
    locale: '',
    symbol: '',
  },
  NGN: {
    countries: ['Nigeria'],
    currency: 'Naira',
    locale: 'ha-NG',
    symbol: '₦',
  },
  NIO: {
    countries: ['Nicaragua'],
    currency: 'Cordoba',
    locale: '',
    symbol: '',
  },
  NOK: {
    countries: ['Norway'],
    currency: 'Krone',
    locale: '',
    symbol: 'kr',
  },
  NPR: {
    countries: ['Nepal'],
    currency: 'Rupee',
    locale: '',
    symbol: '',
  },
  NZD: {
    countries: ['New Zealand'],
    currency: 'Dollar',
    locale: 'en-NZ',
    symbol: '$',
  },
  OMR: {
    countries: ['Oman'],
    currency: 'Rial',
    locale: '',
    symbol: '',
  },
  PAB: {
    countries: ['Panama'],
    currency: 'Balboa',
    locale: '',
    symbol: '',
  },
  PEN: {
    countries: ['Peru'],
    currency: 'Sol',
    locale: '',
  },
  PGK: {
    countries: ['Papua New Guinea'],
    currency: 'Kina',
    locale: '',
    symbol: '',
  },
  PHP: {
    countries: ['Philippines'],
    currency: 'Peso',
    locale: 'fil-PH',
    symbol: '₱',
  },
  PKR: {
    countries: ['Pakistan'],
    currency: 'Rupee',
    locale: '',
  },
  PLN: {
    countries: ['Poland'],
    currency: 'Złoty',
    locale: 'pl-PL',
    symbol: 'zł',
  },
  PYG: {
    countries: ['Paraguay'],
    currency: 'Guarani',
    locale: '',
  },
  QAR: {
    countries: ['Qatar'],
    currency: 'Riyal',
    locale: '',
    symbol: '',
  },
  RON: {
    countries: ['Romania'],
    currency: 'Leu',
    locale: 'ro-RO',
    symbol: '',
  },
  RSD: {
    countries: ['Serbia'],
    currency: 'Dinar',
    locale: '',
    symbol: '',
  },
  RUB: {
    countries: ['Russia'],
    currency: 'Ruble',
    locale: 'ru-RU',
    symbol: '₽',
  },
  RWF: {
    countries: ['Rwanda'],
    currency: 'Franc',
    locale: '',
  },
  SAR: {
    countries: ['Saudi Arabia'],
    currency: 'Riyal',
    locale: '',
    symbol: '',
  },
  SBD: {
    countries: ['Solomon Islands'],
    currency: 'Dollar',
    locale: '',
    symbol: '',
  },
  SCR: {
    countries: ['Seychelles'],
    currency: 'Rupee',
    locale: '',
    symbol: '',
  },
  SDG: {
    countries: ['Sudan'],
    currency: 'Pound',
    locale: '',
    symbol: '',
  },
  SEK: {
    countries: ['Sweden'],
    currency: 'Krona',
    locale: 'sv-SE',
    symbol: 'kr',
  },
  SGD: {
    countries: ['Singapore'],
    currency: 'Dollar',
    locale: 'zh-SG',
    symbol: '',
  },
  SHP: {
    countries: ['Saint Helena'],
    currency: 'Pound',
    locale: '',
    symbol: '',
  },
  SLL: {
    countries: ['Sierra Leone'],
    currency: 'Leone',
    locale: '',
    symbol: '',
  },
  SOS: {
    countries: ['Somalia'],
    currency: 'Shilling',
    locale: '',
    symbol: '',
  },
  SPL: {
    countries: ['Seborga'],
    currency: 'Luigino',
    locale: '',
    symbol: '',
  },
  SRD: {
    countries: ['Suriname'],
    currency: 'Dollar',
    locale: '',
    symbol: '',
  },
  STN: {
    countries: ['São Tomé and Príncipe'],
    currency: 'Dobra',
    locale: '',
    symbol: '',
  },
  SVC: {
    countries: ['El Salvador'],
    currency: 'Colon',
    locale: '',
    symbol: '',
  },
  SYP: {
    countries: ['Syria'],
    currency: 'Pound',
    locale: 'ar-SY',
    symbol: '£S',
  },
  SZL: {
    countries: ['eSwatini'],
    currency: 'Lilangeni',
    locale: '',
    symbol: '',
  },
  THB: {
    countries: ['Thailand'],
    currency: 'Baht',
    locale: 'th-TH',
    symbol: '฿',
  },
  TJS: {
    countries: ['Tajikistan'],
    currency: 'Somoni',
    locale: 'tg-TJ',
    symbol: 'SM',
    fractionDigits: 5,
  },
  TMT: {
    countries: ['Turkmenistan'],
    currency: 'Manat',
    locale: 'tk-TM',
    symbol: 'T',
  },
  TND: {
    countries: ['Tunisia'],
    currency: 'Dinar',
    locale: '',
    symbol: '',
  },
  TOP: {
    countries: ['Tonga'],
    currency: 'Paanga',
    locale: '',
    symbol: '',
  },
  TRY: {
    countries: ['Turkey'],
    currency: 'Lira',
    locale: 'tr-TR',
    symbol: '₺',
  },
  TTD: {
    countries: ['Trinidad and Tobago'],
    currency: 'Dollar',
    locale: '',
    symbol: '',
  },
  TVD: {
    countries: ['Tuvalu'],
    currency: 'Dollar',
    locale: '',
    symbol: '',
  },
  TWD: {
    countries: ['Taiwan'],
    currency: 'New Dollar',
    locale: '',
    symbol: '',
  },
  TZS: {
    countries: ['Tanzania'],
    currency: 'Shilling',
    locale: '',
    symbol: '',
  },
  UAH: {
    countries: ['Ukraine'],
    currency: 'Hryvnia',
    locale: 'uk-UA',
    symbol: '₴',
  },
  UGX: {
    countries: ['Uganda'],
    currency: 'Shilling',
    locale: 'lg-UG',
    symbol: 'USh',
  },
  USD: {
    countries: ['United States'],
    currency: 'Dollar',
    locale: 'en-US',
    symbol: '$',
  },
  UYU: {
    countries: ['Uruguay'],
    currency: 'Peso',
    locale: '',
    symbol: '',
  },
  UZS: {
    countries: ['Uzbekistan'],
    currency: 'Som',
    locale: '',
    symbol: '',
  },
  VEF: {
    countries: ['Venezuela'],
    currency: 'Bolívar',
    locale: '',
    symbol: '',
  },
  VND: {
    countries: ['Viet Nam'],
    currency: 'Dong',
    locale: '',
    symbol: '',
  },
  VUV: {
    countries: ['Vanuatu'],
    currency: 'Vatu',
    locale: '',
    symbol: '',
  },
  WST: {
    countries: ['Samoa'],
    currency: 'Tala',
    locale: '',
    symbol: '',
  },
  XAF: {
    countries: ['Communauté Financière Africaine (BEAC)'],
    currency: ' CFA Franc BEAC',
    locale: '',
    symbol: '',
  },
  XCD: {
    countries: ['East Caribbean'],
    currency: 'Dollar',
    locale: '',
    symbol: '',
  },

  XOF: {
    countries: ['Communauté Financière Africaine (BCEAO)'],
    currency: 'Franc',
    symbol: '',
  },
  XPF: {
    countries: ['Comptoirs Français du Pacifique (CFP)'],
    currency: 'Franc',
    locale: '',
    symbol: '',
  },
  YER: {
    countries: ['Yemen'],
    currency: 'Rial',
    locale: '',
    symbol: '',
    emoji: '🇾🇪',
  },
  ZAR: {
    currency: 'Rand',
    locale: 'en-ZA',
    symbol: 'R',
    code: 'ZAR',
    number: '710',
    plural: 'rand',
    digits: 2,
    subunit: 'cent',
    superunit: 'krugerrand',
    countries: ['Lesotho', 'Namibia', 'South Africa'],
    unofficialUse: [, 'Angola', 'Zambia', 'Zimbabwe'],
  },
  ZMW: {
    countries: ['Zambia'],
    currency: 'Kwacha',
    locale: '',
    symbol: '',
  },
  ZWD: {
    countries: ['Zimbabwe'],
    currency: 'Dollar',
    locale: '',
    symbol: '',
  },
  XXX: {
    currency: '',
    countries: [''],
    locale: '',
    symbol: '',
    unicode: '',
    subunit: '',
    number: '',
    maximumFractionDigits: '',
    minimumFractionDigits: '',
    code: '',
  },
}

const localizedCurrency = (currencyCode, number, display = 'symbol') => {
  const currency = localCurrencyData[currencyCode]
  return new Intl.NumberFormat(currency.locale, {
    style: 'currency',
    currency: currencyCode,
    currencyDisplay: display,
  }).format(number)
}

const costaRica = localizedCurrency('AUD', 300.43)

console.log(Object.keys(localCurrencyData).length)
